doc: fix cashflow /salesgoal example + KPI redirection
myERP/myerp.github.io pull request #22
Opened 2020-10-08 09:33 UTC by Tiity

2020-10-08 18:23 UTC, RomaLefrancois requested changes

2020-10-08 18:23 UTC, RomaLefrancois commented on _includes/1.0/api/json/cash_flow_overtime.json
> +  "currency": "GBP"
Keeps `EUR`

2020-10-08 18:23 UTC, RomaLefrancois commented on _includes/1.0/api/json/cash_flow_overtime.json
> +    "2021-03-31": {
Let's put some real value, not just 0 everywhere.
```
{
  "kpis": {
    "starting_balance_date": "2020-07-01",
    "first_entry_date": "2018-07-06",
    "last_bank_entry_date": "2020-01-02",
    "starting_balance": {
      "amount": 31518.49
    }
  },
  "datas": {
    "2020-07-31": {
      "money_in": {
        "total": 5503.30,
        "forecast": 0,
        "scheduled": 0,
        "completed": 5503.30
      },
      "money_out": {
        "total": -20061.24,
        "forecast": 0,
        "scheduled": 0,
        "completed": -20061.24
      }
    },
    "2020-08-31": {
      "money_in": {
        "total": 9631.54,
        "forecast": 0,
        "scheduled": 0,
        "completed": 9631.54
      },
      "money_out": {
        "total": -21936.43,
        "forecast": 0,
        "scheduled": 0,
        "completed": -21936.43
      }
    },
    "2020-09-30": {
      "money_in": {
        "total": 5562.58,
        "forecast": 0,
        "scheduled": 0,
        "completed": 5562.58
      },
      "money_out": {
        "total": -5601.31,
        "forecast": 0,
        "scheduled": 0,
        "completed": -5601.31
      }
    },
    "2020-10-31": {
      "money_in": {
        "total": 54793.61,
        "forecast": 15210.23,
        "scheduled": 36583.38,
        "completed": 3000.00
      },
      "money_out": {
        "total": -7310.45,
        "forecast": -2405.03,
        "scheduled": -4905.42,
        "completed": 0
      }
    },
    "2020-11-30": {
      "money_in": {
        "total": 2303.91,
        "forecast": 2303.91,
        "scheduled": 0,
        "completed": 0
      },
      "money_out": {
        "total": -2405.03,
        "forecast": -2405.03,
        "scheduled": 0,
        "completed": 0
      }
    },
    "2020-12-31": {
      "money_in": {
        "total": 2303.91,
        "forecast": 2303.91,
        "scheduled": 0,
        "completed": 0
      },
      "money_out": {
        "total": -2421.15,
        "forecast": -2421.15,
        "scheduled": 0,
        "completed": 0
      }
    },
    "2021-01-31": {
      "money_in": {
        "total": 2303.91,
        "forecast": 2303.91,
        "scheduled": 0,
        "completed": 0
      },
      "money_out": {
        "total": -2405.03,
        "forecast": -2405.03,
        "scheduled": 0,
        "completed": 0
      }
    },
    "2021-02-28": {
      "money_in": {
        "total": 2303.91,
        "forecast": 2303.91,
        "scheduled": 0,
        "completed": 0
      },
      "money_out": {
        "total": -2405.03,
        "forecast": -2405.03,
        "scheduled": 0,
        "completed": 0
      }
    },
    "2021-03-31": {
      "money_in": {
        "total": 0,
        "forecast": 0,
        "scheduled": 0,
        "completed": 0
      },
      "money_out": {
        "total": 0,
        "forecast": 0,
        "scheduled": 0,
        "completed": 0
      }
    },
    "2021-04-30": {
      "money_in": {
        "total": 60.00,
        "forecast": 60.00,
        "scheduled": 0,
        "completed": 0
      },
      "money_out": {
        "total": 0,
        "forecast": 0,
        "scheduled": 0,
        "completed": 0
      }
    },
    "2021-05-31": {
      "money_in": {
        "total": 0,
        "forecast": 0,
        "scheduled": 0,
        "completed": 0
      },
      "money_out": {
        "total": 0,
        "forecast": 0,
        "scheduled": 0,
        "completed": 0
      }
    }
  },
  "period_breakdown": "MONTH",
  "currency": "GBP"
}```

2020-10-12 13:53 UTC, fChalmeau approved these changes
👍

2020-10-12 13:53 UTC, merged